export const UPDATE_CLIENT_INFO_PENDING = 'App/UPDATE_CLIENT_INFO_PENDING';
export const UPDATE_CLIENT_INFO_SUCCESS = 'App/UPDATE_CLIENT_INFO_SUCCESS';
export const UPDATE_CLIENT_INFO_ERROR = 'App/UPDATE_CLIENT_INFO_ERROR';

export const ADD_ADDITIONAL_PHONE_NUMBER_TO_CLIENT = 'App/ADD_ADDITIONAL_PHONE_NUMBER_TO_CLIENT';
export const REMOVE_ADDITIONAL_PHONE_NUMBER_TO_CLIENT = 'App/REMOVE_ADDITIONAL_PHONE_NUMBER_TO_CLIENT';

export const OPEN_ADD_CLIENT_CONTACT_MODAL = 'App/OPEN_ADD_CLIENT_CONTACT_MODAL';
export const CLOSE_ADD_CLIENT_CONTACT_MODAL = 'App/CLOSE_ADD_CLIENT_CONTACT_MODAL';

export const OPEN_ADD_PROJECT_CONTACT_MODAL = 'App/OPEN_ADD_PROJECT_CONTACT_MODAL';
export const CLOSE_ADD_PROJECT_CONTACT_MODAL = 'App/CLOSE_ADD_PROJECT_CONTACT_MODAL';

export const  OPEN_MEASUREMENT_APPOINTMENT_MODAL = 'App/OPEN_MEASUREMENT_APPOINTMENT_MODAL';
export const  CLOSE_MEASUREMENT_APPOINTMENT_MODAL = 'App/CLOSE_MEASUREMENT_APPOINTMENT_MODAL';

export const  SUBMIT_PRIMARY_CLIENT_CONTACT_MODAL = 'App/SUBMIT_PRIMARY_CLIENT_CONTACT_MODAL';
export const  SUBMIT_SECONDARY_CLIENT_CONTACT_MODAL = 'App/SUBMIT_SECONDARY_CLIENT_CONTACT_MODAL';
export const  SUBMIT_PROJECT_CONTACT_MODAL = 'App/SUBMIT_PROJECT_CONTACT_MODAL';

export const  ADD_CLIENT_CONTACT = 'App/ADD_CLIENT_CONTACT';
export const  SET_PRIMARY_CLIENT_CONTACT = 'App/SET_PRIMARY_CLIENT_CONTACT';
export const  SET_SECONDARY_CLIENT_CONTACT = 'App/SET_SECONDARY_CLIENT_CONTACT';
export const  ADD_PROJECT_CONTACT = 'App/ADD_PROJECT_CONTACT';


export const  SUBMIT_MEASUREMENT_APPOINTMENT_MODAL = 'App/SUBMIT_MEASUREMENT_APPOINTMENT_MODAL';
export const  ADD_MEASUREMENT_APPOINTMENT = 'App/ADD_MEASUREMENT_APPOINTMENT';
  

